# Site settings
title: PM
email: p@tricks.email
description: > # this means to ignore newlines until "baseurl:"
  Patrick McConlogue
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patrick.ventures" # the base hostname & protocol for your site
twitter_username: aggimagine
github_username:  thnkr

# Build settings
markdown: kramdown
