# Site settings
title: PM
email: pmcconlogue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to store things about the projects that get built.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://patrick.ventures" # the base hostname & protocol for your site
twitter_username: aggimagine
github_username:  thnkr

# Build settings
markdown: kramdown
